import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.home_container}>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.quote_container}>
        <h1>Making sure that your equipment helps you perform your absolute best!</h1>
      </div>
      {/* Services */}
      <h2>Popular Services</h2>
      <div className={styles.image_container}>
        <div className={styles.image_container_flex_item}>
          <h3>Stringing</h3>
          <div className={styles.image}>
            <Image
              src='/assets/tennis/stringing1.jpg'
              alt='stringing'
              layout="fill"
              priority
            />
          </div>
        </div>
        <div className={styles.image_container_flex_item}>
          <h3>Regripping</h3>
          <div className={styles.image}>
            <Image
              src='/assets/tennis/regrip.jpeg'
              alt='stringing'
              layout="fill"
              priority
            />
          </div>
        </div>
        <div className={styles.image_container_flex_item}>
          <h3>Lead Tape</h3>
          <div className={styles.image}>
            <Image
              src='/assets/tennis/leadtape1.jpg'
              alt='stringing'
              layout="fill"
            />
          </div>
        </div>
        <div className={styles.image_container_flex_item}>
          <h3>Grip Building</h3>
          <div className={styles.image}>
            <Image
              src='/assets/tennis/gripbuild.jpg'
              alt='stringing'
              layout="fill"
            />
          </div>
        </div>
      </div>
      {/* Consulting */}
      <h2>Consulting</h2>
      <div className={styles.consulting_container}>
        <div className={styles.consulting_container_flex_item}>
          <FontAwesomeIcon icon="question" className={styles.icon} />
          <div>What racket should I use?</div>
        </div>
        <div className={styles.consulting_container_flex_item}>
          <FontAwesomeIcon icon="weight" className={styles.icon} />
          <div>What tension should I string my racket?</div>
        </div>
        <div className={styles.consulting_container_flex_item}>
          <FontAwesomeIcon icon="ruler" className={styles.icon} />
          <div>How big of a grip do I need?</div>
        </div>
        <div className={styles.consulting_container_flex_item}>
          <FontAwesomeIcon icon="dumbbell" className={styles.icon} />
          <div>How heavy should my racket be?</div>
        </div>
      </div>
    </div>
  )
}

export default Home
